_
USE [master]
GO
/****** Object:  Database [Buse]    Script Date: 2025/02/11 19:45:10 ******/
DROP DATABASE [Buse]
GO
/****** Object:  Database [Buse]    Script Date: 2025/02/11 19:45:10 ******/
CREATE DATABASE [Buse]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Buse', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.LIWS\MSSQL\DATA\Buse.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Buse_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.LIWS\MSSQL\DATA\Buse_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Buse] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Buse].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Buse] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Buse] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Buse] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Buse] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Buse] SET ARITHABORT OFF 
GO
ALTER DATABASE [Buse] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Buse] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Buse] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Buse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Buse] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Buse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Buse] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Buse] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Buse] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Buse] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Buse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Buse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Buse] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Buse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Buse] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Buse] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Buse] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Buse] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Buse] SET  MULTI_USER 
GO
ALTER DATABASE [Buse] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Buse] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Buse] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Buse] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Buse] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Buse] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Buse] SET QUERY_STORE = ON
GO
ALTER DATABASE [Buse] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Buse]
GO
/****** Object:  Table [dbo].[Transanctions]    Script Date: 2025/02/11 19:45:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transanctions](
	[Transaction_No] [int] IDENTITY(1,1) NOT NULL,
	[Transaction_Description] [varchar](200) NOT NULL,
	[Transaction_Amount] [float] NOT NULL,
	[Transaction_Date] [datetime] NOT NULL,
 CONSTRAINT [PK_Transanctions] PRIMARY KEY CLUSTERED 
(
	[Transaction_No] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Transanctions] ON 
GO
INSERT [dbo].[Transanctions] ([Transaction_No], [Transaction_Description], [Transaction_Amount], [Transaction_Date]) VALUES (2, N'First Transaction', 12.2, CAST(N'2024-02-11T08:30:00.000' AS DateTime))
GO
INSERT [dbo].[Transanctions] ([Transaction_No], [Transaction_Description], [Transaction_Amount], [Transaction_Date]) VALUES (3, N'Second Transaction', 18.2, CAST(N'2024-02-11T09:30:00.000' AS DateTime))
GO
INSERT [dbo].[Transanctions] ([Transaction_No], [Transaction_Description], [Transaction_Amount], [Transaction_Date]) VALUES (4, N'Third Transaction', 20, CAST(N'2024-02-11T11:30:00.000' AS DateTime))
GO
INSERT [dbo].[Transanctions] ([Transaction_No], [Transaction_Description], [Transaction_Amount], [Transaction_Date]) VALUES (5, N'Forth Transaction', 30, CAST(N'2024-02-11T14:00:00.000' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Transanctions] OFF
GO
USE [master]
GO
ALTER DATABASE [Buse] SET  READ_WRITE 
GO
